theme: jekyll-theme-minimal
title: ğŸ“
description: |
  ğŸ  Lille, France
  <br/>
  <a href="tel:+33 7 82 33 53 54">ğŸ“±ğŸ‡«ğŸ‡· +33 7 82 33 53 54</a>
  <br/>
  <a href="mailto:salladiagne14@gmail.com"><img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&amp;logo=gmail&amp;logoColor=white" alt=""></a>
  <br/>
  <img href=https://img.shields.io/badge/-12100E?&amp;logo=github&amp;logoColor=white"/> <a href="https://github.com/sallareznov">Github</a>
  <br/>
  <a href="https://www.linkedin.com/in/salladiagne/"><img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&amp;logo=linkedin&amp;logoColor=white" alt="LinkedIn"></a>
  <br/>
  <a href="https://medium.com/@sallareznov"><img src="https://img.shields.io/badge/Medium-12100E?style=for-the-badge&amp;logo=medium&amp;logoColor=white" alt=""></a>
