theme: jekyll-theme-minimal
description: |
  ğŸ  Lille, France
  ğŸ“± ğŸ‡«ğŸ‡· +33 7 82 33 53 54
  <br/>
  <a href="mailto:salladiagne14@gmail.com">ğŸ“§ Email</a>
  <br/>
  <a href="https://github.com/sallareznov">ğŸ‘¨ğŸ¾â€ğŸ’» Github</a>
  <br/>
  <a href="https://github.com/sallareznov">ğŸ–‡ï¸ LinkedIn</a>

