theme: jekyll-theme-minimal
title: ğŸ“
description: |
  ğŸ  Lille, France
  <br/>
  <a href="tel:+33 7 82 33 53 54">ğŸ“±ğŸ‡«ğŸ‡· +33 7 82 33 53 54</a>
  <br/>
  <a href="mailto:salladiagne14@gmail.com">ğŸ“§ Email</a>
  <br/>
  <a href="https://github.com/sallareznov">ğŸ‘¨ğŸ¾â€ğŸ’» Github</a>
  <br/>
  <a href="https://www.linkedin.com/in/salladiagne/">ğŸ–‡ï¸ LinkedIn</a>
  <br/>
  <a href="https://medium.com/@sallareznov">ğŸ“ Medium</a>
